### Positive: User can deposit to account amount 4999,99
POST {{baseUrl}}/api/v1/accounts/deposit
Content-Type: application/json
Accept: */*
Authorization: {{authToken2}}

{
  "id": 1,
  "balance": 4999.99
}

